/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerProduk;
import Controller.ControllerJenisBarang;
import Controller.ControllerTransaksi;
import Controller.ControllerUser;
import Models.ProdukModel;
import Models.JenisBarangModel;
import Models.TransaksiModel;
import Models.UserModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario Chamdjoko Jati
 */
public class MainAdmin extends javax.swing.JFrame {

    private ControllerProduk conBar;
    private ControllerProduk conJenis;
    private ControllerUser conUser;
    private ControllerTransaksi conTrans;

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
        loadBarang();
        loadUser();
        loadTrx();
        jLabel7.setText("");
    }

    private void clearData() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jLabel7.setText("");
    }

    private void loadBarang() {
        List<ProdukModel> lsBarang = new ArrayList<ProdukModel>();
        conBar = new Controller.ControllerProduk();
        lsBarang = conBar.getBrg();

        Object[][] obBar = new Object[lsBarang.size()][6];

        int i = 0;

        for (ProdukModel bm : lsBarang) {
            obBar[i][0] = bm.getID_Produk();
            obBar[i][1] = bm.getNama_Produk();
            obBar[i][2] = bm.getHarga();
            obBar[i][3] = bm.getJenis();
            i++;
        }
        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
                obBar,
                new String[] {
                        "ID Barang", "Nama Produk", "Harga", "Jenis"
                }));
        TableBarang.setDefaultEditor(Object.class, null);
    }

    private void loadUser() {
        List<UserModel> lsUser = new ArrayList<UserModel>();
        conUser = new ControllerUser();
        lsUser = conUser.getUser();

        Object[][] obUser = new Object[lsUser.size()][4];

        int i = 0;

        for (UserModel um : lsUser) {
            obUser[i][0] = um.getID_User();
            obUser[i][1] = um.getUsername();
            obUser[i][2] = um.getPassword();
            obUser[i][3] = um.getNama();
            i++;
        }
        TableUser.setModel(new javax.swing.table.DefaultTableModel(
                obUser,
                new String[] {
                        "ID User", "Username", "Password", "Nama"
                }));
        TableUser.setDefaultEditor(Object.class, null);
    }

    private void loadTrx() {
        List<TransaksiModel> lsTrans = new ArrayList<TransaksiModel>();
        conTrans = new ControllerTransaksi();
        lsTrans = conTrans.getTrx();

        Object[][] obTrans = new Object[lsTrans.size()][6];

        int i = 0;

        for (TransaksiModel um : lsTrans) {
            obTrans[i][0] = um.getID_Transaksi();
            obTrans[i][1] = um.getID_Produk();
            obTrans[i][2] = um.getID_User();
            obTrans[i][3] = um.getJumlah();
            obTrans[i][4] = um.getTotal();
            i++;
        }
        TableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
                obTrans,
                new String[] {
                        "ID Transaksi", "ID Produk", "ID User", "Jumlah", "Total"
                }));
        TableTransaksi.setDefaultEditor(Object.class, null);
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableTransaksi = new javax.swing.JTable();
        LOGOUT3 = new javax.swing.JButton();
        BARANG2 = new javax.swing.JButton();
        USER2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        LOGOUT2 = new javax.swing.JButton();
        TRANSAKSI2 = new javax.swing.JButton();
        BARANG1 = new javax.swing.JButton();
        DELETEUSER = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        LOGOUT1 = new javax.swing.JButton();
        USER1 = new javax.swing.JButton();
        TRANSAKSI1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TableTransaksi);

        LOGOUT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-out.png"))); // NOI18N
        LOGOUT3.setText("Logout");
        LOGOUT3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT3ActionPerformed(evt);
            }
        });

        BARANG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laptop.png"))); // NOI18N
        BARANG2.setText("Barang");
        BARANG2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BARANG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BARANG2ActionPerformed(evt);
            }
        });

        USER2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        USER2.setText("User");
        USER2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USER2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data Transaksi");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel10)
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LOGOUT3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BARANG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(USER2)))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGOUT3)
                    .addComponent(USER2)
                    .addComponent(BARANG2))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(TableUser);

        LOGOUT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-out.png"))); // NOI18N
        LOGOUT2.setText("Logout");
        LOGOUT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT2ActionPerformed(evt);
            }
        });

        TRANSAKSI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/receipt.png"))); // NOI18N
        TRANSAKSI2.setText("Transaksi");
        TRANSAKSI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TRANSAKSI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRANSAKSI2ActionPerformed(evt);
            }
        });

        BARANG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/laptop.png"))); // NOI18N
        BARANG1.setText("Barang");
        BARANG1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BARANG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BARANG1ActionPerformed(evt);
            }
        });

        DELETEUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash.png"))); // NOI18N
        DELETEUSER.setText("Delete");
        DELETEUSER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETEUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEUSERActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 45));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data User");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel9)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LOGOUT2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DELETEUSER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TRANSAKSI2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BARANG1)))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGOUT2)
                    .addComponent(BARANG1)
                    .addComponent(TRANSAKSI2)
                    .addComponent(DELETEUSER))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBarang);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama Produk");

        jTextField1.setForeground(new java.awt.Color(51, 51, 51));

        jTextField2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jenis");

        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Tambah Barang");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Barang");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete Barang");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ID Barang");

        jButton4.setText("Reset");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        LOGOUT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-out.png"))); // NOI18N
        LOGOUT1.setText("Logout");
        LOGOUT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT1ActionPerformed(evt);
            }
        });

        USER1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        USER1.setText("User");
        USER1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        USER1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USER1ActionPerformed(evt);
            }
        });

        TRANSAKSI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/receipt.png"))); // NOI18N
        TRANSAKSI1.setText("Transaksi");
        TRANSAKSI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TRANSAKSI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRANSAKSI1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Barang");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LOGOUT1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TRANSAKSI1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(USER1)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(69, 69, 69)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8))
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(40, 40, 40))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGOUT1)
                    .addComponent(USER1)
                    .addComponent(TRANSAKSI1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void DELETEUSERActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DELETEUSERActionPerformed
        int opt = JOptionPane.showConfirmDialog(this, "Apakah yakin akan menghapus user ini?", "Delete User",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            int row = TableUser.getSelectedRow();
            int id_user = Integer.parseInt(TableUser.getValueAt(row, 0).toString());
            conUser = new ControllerUser();
            UserModel um = new UserModel();
            um.setID_User(id_user);
            conUser.deleteUser(um);
            loadUser();
            JOptionPane.showMessageDialog(this, "Data User Berhasil dihapus!!");
        }

    }// GEN-LAST:event_DELETEUSERActionPerformed

    private void LOGOUT3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LOGOUT1ActionPerformed
        new MainLogin().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_LOGOUT1ActionPerformed

    private void USER2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TRANSAKSI2ActionPerformed
        jPanel3.hide();
        jPanel2.show();
    }// GEN-LAST:event_TRANSAKSI2ActionPerformed

    private void BARANG2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_USER2ActionPerformed
        jPanel3.hide();
        jPanel1.show();
    }// GEN-LAST:event_USER2ActionPerformed

    private void LOGOUT2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LOGOUT2ActionPerformed
        new MainLogin().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_LOGOUT2ActionPerformed

    private void BARANG1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TRANSAKSI3ActionPerformed
        jPanel2.hide();
        jPanel1.show();
    }// GEN-LAST:event_TRANSAKSI3ActionPerformed

    private void TRANSAKSI2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_USER3ActionPerformed
        jPanel2.hide();
        jPanel3.show();
    }// GEN-LAST:event_USER3ActionPerformed

    private void USER1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_USER1ActionPerformed
        jPanel1.hide();
        jPanel2.show();
    }// GEN-LAST:event_USER1ActionPerformed

    private void TRANSAKSI1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TRANSAKSI1ActionPerformed
        jPanel1.hide();
        jPanel3.show();
    }// GEN-LAST:event_TRANSAKSI1ActionPerformed

    private void LOGOUT1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LOGOUTActionPerformed
        new MainLogin().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_LOGOUTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        loadBarang();
        clearData();
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        String tipe;
        int ID_Barang, hasil = 0;
        ID_Barang = Integer.parseInt(jLabel7.getText());
        tipe = jTextField1.getText();

        int quest = JOptionPane.showConfirmDialog(this, "Yakin Ingin Menghapus Data " + tipe + "?", "Info",
                JOptionPane.YES_NO_OPTION);

        if (quest == JOptionPane.YES_OPTION) {
            ProdukModel bm = new ProdukModel();
            bm.setID_Produk(ID_Barang);

            conJenis = new ControllerProduk();
            hasil = conJenis.deleteBrg(bm);

            if (hasil == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus!");
            }

            loadBarang();
            clearData();
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        int hasil = 0;
        conBar = new ControllerProduk();
        
        String nama = jTextField1.getText();
        int Harga = Integer.parseInt(jTextField2.getText());
        String jenis = jTextField3.getText();

        if ((jTextField1.equals("")) || (jTextField2.equals(""))
                || (jTextField3.equals(""))
                ) {
            JOptionPane.showMessageDialog(null, "Fill all the required fields!!");
        } else {
            ProdukModel bm = new ProdukModel(nama, Harga, jenis);
            hasil = conBar.saveBrg(bm);
            switch (hasil) {
                case 1:
                    JOptionPane.showMessageDialog(this, "Barang Berhasil ditambahkan");
                    loadBarang();
                    clearData();
                    break;
                case -1:
                    JOptionPane.showMessageDialog(this, "Tipe tersebut telah didaftarkan");
                    jTextField1.requestFocusInWindow();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Data Gagal Disimpan");
                    break;
            }
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        int hasil = 0;
        conBar = new ControllerProduk();

        int ID_Barang = Integer.parseInt(jLabel7.getText());
        String nama = jTextField1.getText();
        int Harga = Integer.parseInt(jTextField2.getText());
        String jenis = jTextField3.getText();

        if ( (jTextField1.equals("")) || (jTextField2.equals(""))
                || (jTextField3.equals(""))
              ) {
            JOptionPane.showMessageDialog(null, "Fill all the required fields!!");
        } else {
            ProdukModel bm = new ProdukModel(ID_Barang, nama, Harga, jenis);
            hasil = conBar.updateBrg(bm);
            if (hasil == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diedit!");
                loadBarang();
                clearData();
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Diedit!");
            }
        }

    }// GEN-LAST:event_jButton2ActionPerformed

    private void TableBarangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TableBarangMouseClicked
        int row = TableBarang.getSelectedRow();
        int ID_Barang = Integer.parseInt(TableBarang.getValueAt(row, 0).toString());
        String nama = TableBarang.getValueAt(row, 1).toString();
        int Harga = Integer.parseInt(TableBarang.getValueAt(row, 2).toString());
        String jenis = TableBarang.getValueAt(row, 3).toString();
        jTextField1.setText(nama);
        jTextField3.setText(jenis);
        jTextField2.setText(String.valueOf(Harga));
        jLabel7.setText(String.valueOf(ID_Barang));
    }// GEN-LAST:event_TableBarangMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BARANG1;
    private javax.swing.JButton BARANG2;
    private javax.swing.JButton DELETEUSER;
    private javax.swing.JButton LOGOUT1;
    private javax.swing.JButton LOGOUT2;
    private javax.swing.JButton LOGOUT3;
    private javax.swing.JButton TRANSAKSI1;
    private javax.swing.JButton TRANSAKSI2;
    private javax.swing.JTable TableBarang;
    private javax.swing.JTable TableTransaksi;
    private javax.swing.JTable TableUser;
    private javax.swing.JButton USER1;
    private javax.swing.JButton USER2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
