/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package View;

import Controller.ControllerProduk;
import Controller.ControllerKeranjang;
import Controller.ControllerTransaksi;
import Models.ProdukModel;
import Models.KeranjangModel;
import Models.TransaksiModel;
import Models.UserModel;


import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class MainMenu extends javax.swing.JFrame {

        private ControllerProduk conBar;
        public static UserModel mLogin;
        private ControllerKeranjang conCart;
        private ControllerTransaksi conTrans;
        
        /**
         * Creates new form MainMenu
         */
        public MainMenu(UserModel mLogin) {
                initComponents();
                clearData();
                loadBarang();
                loadCart();
                JUMLAH.setText("1");
        }

        private void clearData() {
                IDPRODUK.setText("");
                NAMAPRODUK.setText("");
                TIPE.setText("");
                HARGA.setText("");
                JUMLAH.setText("1");
                TOTAL.setText("");
                SUBTOTAL.setText("");
        }

        private void loadCart() {
                int total = 0;
                List<KeranjangModel> lsCart = new ArrayList<KeranjangModel>();
                conCart = new Controller.ControllerKeranjang();
                lsCart = conCart.getCart(mLogin);

                Object[][] obCart = new Object[lsCart.size()][7];

                int i = 0;

                for (KeranjangModel cm : lsCart) {
                        obCart[i][0] = cm.getID_User();
                        obCart[i][1] = cm.getID_Produk();
                        obCart[i][2] = cm.getNama_Produk();
                        obCart[i][3] = cm.getJenis();
                        obCart[i][4] = cm.getHarga();
                        obCart[i][5] = cm.getJumlah();
                        obCart[i][6] = cm.getTotal();
                        total += cm.getTotal();
                        i++;
                }
                SUBTOTAL.setText(String.valueOf(total));
                TableCart.setModel(new javax.swing.table.DefaultTableModel(
                                obCart,
                                new String[] {
                                                "ID_User", "ID Produk", "Nama Produk", "Jenis", "Harga", "Jumlah", "Total"
                                }));
                TableBarang.setDefaultEditor(Object.class, null);
        }

        private void loadBarang() {
                List<ProdukModel> lsBarang = new ArrayList<ProdukModel>();
                conBar = new Controller.ControllerProduk();
                lsBarang = conBar.getBrg();

                Object[][] obBar = new Object[lsBarang.size()][6];
                
                int i = 0;
                    
                for (ProdukModel bm : lsBarang) {
                        System.out.println(bm);
                        obBar[i][0] = bm.getID_Produk();
                        obBar[i][1] = bm.getNama_Produk();
                        obBar[i][2] = bm.getJenis();
                        obBar[i][3] = bm.getHarga();
                        i++;
                }
                TableBarang.setModel(new javax.swing.table.DefaultTableModel(
                                obBar,
                                new String[] {
                                                "ID Produk", "Nama Produk", "Jenis", "Harga"
                                }));
                TableBarang.setDefaultEditor(Object.class, null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBarang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCart = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        IDPRODUK = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NAMAPRODUK = new javax.swing.JLabel();
        TIPE = new javax.swing.JLabel();
        HARGA = new javax.swing.JLabel();
        JUMLAH = new javax.swing.JTextField();
        TOTAL = new javax.swing.JLabel();
        Cart = new javax.swing.JButton();
        SUBTOTAL = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DeleteCart = new javax.swing.JButton();
        CO = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zeal");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBarang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 680, 220));

        TableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(TableCart);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 680, 220));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Produk      :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, -1, -1));

        IDPRODUK.setBackground(new java.awt.Color(0, 0, 0));
        IDPRODUK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IDPRODUK.setText("-");
        jPanel1.add(IDPRODUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 105, 15));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nama Produk :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jenis               :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Harga             :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah            :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total               :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        NAMAPRODUK.setBackground(new java.awt.Color(0, 0, 0));
        NAMAPRODUK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(NAMAPRODUK, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 105, 15));

        TIPE.setBackground(new java.awt.Color(0, 0, 0));
        TIPE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(TIPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 101, 15));

        HARGA.setBackground(new java.awt.Color(0, 0, 0));
        HARGA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(HARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 102, 19));

        JUMLAH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JUMLAH.setText("1");
        JUMLAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUMLAHActionPerformed(evt);
            }
        });
        JUMLAH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JUMLAHKeyPressed(evt);
            }
        });
        jPanel1.add(JUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 101, -1));

        TOTAL.setBackground(new java.awt.Color(0, 0, 0));
        TOTAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 99, 15));

        Cart.setText("Tambah Ke Keranjang");
        Cart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartActionPerformed(evt);
            }
        });
        jPanel1.add(Cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        SUBTOTAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SUBTOTAL.setText("SUBTOTAL");
        jPanel1.add(SUBTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 590, 101, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Sub Total       :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        DeleteCart.setText("Hapus Dari Keranjang");
        DeleteCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCartActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        CO.setText("Checkout");
        CO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COActionPerformed(evt);
            }
        });
        jPanel1.add(CO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, -1, -1));

        LOGOUT.setText("Logout");
        LOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });
        jPanel1.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Zeal Coffee");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel1)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void JUMLAHKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_JUMLAHKeyPressed

        }// GEN-LAST:event_JUMLAHKeyPressed

        private void JUMLAHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JUMLAHActionPerformed
                if ((Integer.parseInt(JUMLAH.getText()) < 1) || (JUMLAH.equals(""))) {
                        JUMLAH.setText("1");
                }
                TOTAL.setText(String.valueOf(Integer.parseInt(HARGA.getText()) * Integer.parseInt(JUMLAH.getText())));
        }// GEN-LAST:event_JUMLAHActionPerformed

        private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LOGOUTActionPerformed
                new MainLogin().setVisible(true);
                this.dispose();
        }// GEN-LAST:event_LOGOUTActionPerformed

        private void TableBarangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TableBarangMouseClicked
                int row = TableBarang.getSelectedRow();
                IDPRODUK.setText(TableBarang.getValueAt(row, 0).toString());
                NAMAPRODUK.setText(TableBarang.getValueAt(row, 1).toString());
                TIPE.setText(TableBarang.getValueAt(row, 2).toString());
                HARGA.setText(TableBarang.getValueAt(row, 3).toString());
                TOTAL.setText(String.valueOf(Integer.parseInt(HARGA.getText()) * Integer.parseInt(JUMLAH.getText())));
        }// GEN-LAST:event_TableBarangMouseClicked

        private void COActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_COActionPerformed
                conTrans = new ControllerTransaksi();
                conBar = new ControllerProduk();
                conCart = new ControllerKeranjang();

                Object[][] obCart = new Object[TableCart.getRowCount()][TableCart.getColumnCount()];

                int i = 0;
                try {
                        for (i = 0; i < TableCart.getRowCount(); i++) {
                                ProdukModel bm = new ProdukModel();
                                obCart[i][0] = TableCart.getValueAt(i, 0);// id user
                                obCart[i][1] = TableCart.getValueAt(i, 1);// id produk
                                obCart[i][2] = TableCart.getValueAt(i, 2);// nama produk
                                obCart[i][3] = TableCart.getValueAt(i, 3);// jenis
                                obCart[i][4] = TableCart.getValueAt(i, 4);// harga
                                obCart[i][5] = TableCart.getValueAt(i, 5);// jumlah
                                obCart[i][6] = TableCart.getValueAt(i, 6);// total
                                TransaksiModel tm = new TransaksiModel(Integer.parseInt(
                                                obCart[i][0].toString()), mLogin.getID_User(),
                                                Integer.parseInt(obCart[i][5].toString()),
                                                Integer.parseInt(obCart[i][6].toString()));
                                conTrans.saveTrx(tm);
                        }
                        conCart.deleteCart(mLogin);
                        loadCart();
                        loadBarang();
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Gagal menambahkan data", "Failed",
                                        JOptionPane.ERROR_MESSAGE);
                }

        }// GEN-LAST:event_COActionPerformed

        private void DeleteCartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeleteCartActionPerformed
                int hasil = 0;
                int quest = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data keranjang?", "Delete Cart",
                                JOptionPane.YES_NO_OPTION);
                if (quest == JOptionPane.YES_OPTION) {
                        conCart = new ControllerKeranjang();
                        hasil = conCart.deleteCart(mLogin);

                        if (hasil == 1) {
                                JOptionPane.showMessageDialog(this, "Cart berhasil dihapus");
                        } else {
                                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
                        }
                        loadCart();
                }
        }// GEN-LAST:event_DeleteCartActionPerformed

        private void CartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_CartActionPerformed
                int hasil = 0;
                conCart = new ControllerKeranjang();
                if (IDPRODUK.equals("") || NAMAPRODUK.equals("") || JUMLAH.equals("") || TIPE.equals("")
                                || TOTAL.equals("")) {
                        JOptionPane.showMessageDialog(this, "Pilih barang terlebih dahulu!!");
                } else if (HARGA.equals("")) {
                        JOptionPane.showMessageDialog(this, "Isi kolom harga terlebih dahulu!!!");
                } else {
                        KeranjangModel cm = new KeranjangModel(mLogin.getID_User(), Integer.parseInt(IDPRODUK.getText()), 
                                        NAMAPRODUK.getText(),Integer.parseInt(JUMLAH.getText()),
                                        Integer.parseInt(HARGA.getText()), TIPE.getText(),
                                        Integer.parseInt(TOTAL.getText()));
                        hasil = conCart.saveCart(cm);
                        if (hasil == 1) {
                                JOptionPane.showMessageDialog(this, "Berhasil menambahkan ke keranjang",
                                                "Berhasil",
                                                JOptionPane.INFORMATION_MESSAGE);
                        } else {
                                JOptionPane.showMessageDialog(this, "Gagal Menambahkan barang ke keranjang", "GAGAL!",
                                                JOptionPane.ERROR_MESSAGE);
                        }
                }
                clearData();
                loadCart();
        }// GEN-LAST:event_CartActionPerformed

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CO;
    private javax.swing.JButton Cart;
    private javax.swing.JButton DeleteCart;
    private javax.swing.JLabel HARGA;
    private javax.swing.JLabel IDPRODUK;
    private javax.swing.JTextField JUMLAH;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JLabel NAMAPRODUK;
    private javax.swing.JLabel SUBTOTAL;
    private javax.swing.JLabel TIPE;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JTable TableBarang;
    private javax.swing.JTable TableCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
